version: "3.9"
services:
  node:
    image: xlonelyplayer/node-app:1.0
    container_name: node-app
    networks:
      - node-app-compose-bridge
    ports:
      - 3001:3001
    depends_on:
      - mariadb
  mariadb:
    image: xlonelyplayer/mariadb:1.0
    container_name: mariadb
    networks:
      - node-app-compose-bridge
    environment:
      - MARIADB_ROOT_PASSWORD=Password123!
    ports:
      - 3306:3306

networks:
  node-app-compose-bridge:
    driver: bridge