version: "3.9"
services:
  node:
    image: xlonelyplayer/node-app:1.0
    container_name: node-app
    networks:
      - node-app-compose-bridge
    ports:
      - 3001:3001

networks:
  node-app-compose-bridge:
    driver: bridge